name: build the package

on: push

jobs:
    build:
        name: build distribution
        runs-on: macos-latest

        steps:
        - name: setup Python
          uses: actions/checkout@v4
          with:
            python-version: "3.x"
        - name: install build
          run: python3 -m pip install build
        - name: build wheel + tarball
          run: python3 -m build
        - name: store the package
          uses: actions/upload-artifact@v4
          with:
            name: python-package-distributions
            path: dist/
